### ISSUE TITLE
Bug: SMTP throws AttributeError on teardown

### ISSUE THREAD

**Issue by henri-hulski** [pytest-dev/pytest-localserver#53]
It seems smtp server isn't compatible anymore with the recent aiosmtpd vesrsion.
I'm getting the following error when teardown the smtp server. Before everything worked fine.
```
______________________________ ERROR at teardown of test_admin_permissions ______________________________

    @pytest.fixture(scope="session")
    def smtp_server():
        from pytest_localserver import smtp
    
        port = 3377
        server = smtp.Server(port=port)
        server.start()
        yield server
>       server.stop()

myapplication/tests/conftest.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <smtp.Server 127.0.0.1:3377>, timeout = None

    def stop(self, timeout=None):
        """
        Stops test server.
        :param timeout: When the timeout argument is present and not None, it
        should be a floating point number specifying a timeout for the
        operation in seconds (or fractions thereof).
        """
    
        # This mostly copies the implementation from Controller.stop(), with two
        # differences:
        # - It removes the assertion that the thread exists, allowing stop() to
        #   be called more than once safely
        # - It passes the timeout argument to Thread.join()
        if self.loop.is_running():
>           self.loop.call_soon_threadsafe(self._stop)
E           AttributeError: 'Server' object has no attribute '_stop'

__pypackages__/3.9/lib/pytest_localserver/smtp.py:133: AttributeError
```

**Comment by diazona** [comment]
Darn, well thanks for pointing this out! Would you be interested in fixing this yourself? If not, I can work on it sometime soon, maybe this weekend or next week.

**Comment by henri-hulski** [comment]
Sure I can take a look. Seems that private method (`_stop`), which was removed. Not sure if it just can be replaced with the public `stop` method?

**Comment by diazona** [comment]
I guess you might as well try it and find out. I'm not super familiar with the aiosmtpd API; I've never used it myself aside from this project.

**Comment by henri-hulski** [comment]
Do you know why pytest-localserver actually was using the private method in the first place?

**Comment by henri-hulski** [comment]
https://github.com/pytest-dev/pytest-localserver/blob/master/pytest_localserver/smtp.py#L133

**Comment by henri-hulski** [comment]
I will take a look tomorrow. Here it's already 1:00 am.

**Comment by diazona** [comment]
No problem, thanks for being willing to help!

I see the comment in the source code says I copied the implementation of `aiosmtpd.controller.Controller.stop()`, with a couple changes to keep the behavior of the `Server.stop()` method consistent with older versions of pytest-localserver. So I don't think it calls `_stop()` for any reason other than that `Controller.stop()` does. Of course it would have been better to use a public API instead of the private method, but I couldn't find a suitable API in `aiosmtpd`, and I was just trying to do something quick to break our dependency on the deprecated `smtpd` module from Python's standard library. I seem to remember that if I didn't call it, something went wrong, but I don't remember what exactly that was - it's been a while.

**Comment by henri-hulski** [comment]
It was quite easy to fix . In aiosmtpd the `_stop` method was replaced by `cancel_tasks`.
